### ISSUE TITLE
User watchlist

### ISSUE THREAD

**Issue by xdk78** [xdk78/senren-backend#14]
- Watching
- Completed
- On-Hold
- Dropped
- Plan to Watch

**Comment by feelfreelinux** [comment]
Still left:
- Completed
- On-Hold
- Dropped
- Plan to Watch

**Comment by xdk78** [comment]
@feelfreelinux  https://github.com/xdk78/senren-backend/commit/3cfab09201dac962dae9d9f67f3b672de6a4eed2

**Comment by feelfreelinux** [comment]
o shit
